seed_everything: 1337
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 50
  accumulate_grad_batches: 8
  gradient_clip_val: 0.5
  check_val_every_n_epoch: 1
  log_every_n_steps: 5
  callbacks:
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: ModelCheckpoint
      init_args:
        monitor: val_loss
        mode: min
        save_last: true
        filename: "model-{epoch:02d}-{val_loss:.2f}"
